site_name: ShingakuDoc
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
    - 'Introduction': 'docs/kojin/base/index.md'
    - 'Kojin Search': 'docs/kojin/base/kojin.md'
