site_name: ShingakuDoc
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
    - 'Introduction': kojin/base.md
    - 'Kojin Search': kojin/kojin.md
